### ISSUE TITLE
Opdracht 1.2

### ISSUE THREAD

**Issue by pp-koch** [TimTerwijn/browser-technologies-1920#1]
Ontbreekt: link naar de app. Ik heb 'm niet zelf kunnen zien, en begrijp dus niet waarom ontbreken van een toetsenbord een probleem is.

* een beschrijving van alle features die je hebt getest

	Goed.
	
* een beschrijving van de Devices en browsers waar je op hebt getest

	Goed.

* een beschrijving van de screenreader test

	Goed

* beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben

	Deze is wat minder. Je noemt een aantal problemen, maar geeft nergens aan hoe je ze zou oplossen. Waarom werkt de app slecht in IE 11 en de iPad? Wat doe je aan het kleine scherm op de LG Nexus?
	
	Ik zou graag de technische oorzaken van de problemen weten, en wat je er precies aan gaat doen.

**Comment by SynthWeaver** [comment]
Bedankt voor je feedback! Ik ga ermee aan de slag!
